package zasellaid.dao.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import zasellaid.dao.entity.ClientUser;

public interface ClientUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int insert(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int insertSelective(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	ClientUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ClientUser record);

	@Select("select * from t_client_user where phone=#{phone} and password_md5 = #{passwordMd5}")
	@ResultMap("zasellaid.dao.mapper.ClientUserMapper.BaseResultMap")
	ClientUser loginByPhoneAndPwdCheck(@Param("phone") String phone, @Param("passwordMd5") String passwordMd5);

	@Select("select count(1) from t_client_user where phone=#{phone}")
	int phoneCheck(@Param("phone") String phone);

	@Select("select * from t_client_user where phone=#{phone}")
	@ResultMap("zasellaid.dao.mapper.ClientUserMapper.BaseResultMap")
	ClientUser getByPhone(@Param("phone") String phone);

	@Select("select password_md5 from t_client_user where id=#{userId}")
	String getPasswordMd5(@Param("userId") String userId);
}