package zasellaid.dao.mapper;

import zasellaid.dao.entity.ContactHospital;

public interface ContactHospitalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	int insert(ContactHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	int insertSelective(ContactHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	ContactHospital selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ContactHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_contact_hospital
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ContactHospital record);
}