package zasellaid.dao.mapper;

import java.math.BigDecimal;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import zasellaid.dao.entity.Sysparam;

public interface SysparamMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	int insert(Sysparam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	int insertSelective(Sysparam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	Sysparam selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Sysparam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_sysparam
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Sysparam record);

	@Select("select value from t_sysparam where id=#{id}")
	@ResultType(String.class)
	String getStringValue(@Param("id") String id);

	@Select("select value from t_sysparam where id=#{id}")
	@ResultType(Integer.class)
	Integer getIntegerValue(@Param("id") String id);

	@Select("select value from t_sysparam where id=#{id}")
	@ResultType(BigDecimal.class)
	BigDecimal getDecimalValue(@Param("id") String id);

	@Update("update t_sysparam set value=#{value} where id=#{id}")
	int updateValue(@Param("id") String id, @Param("value") String value);
}