package zasellaid.dao.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;

import zasellaid.dao.entity.TraceRecord;

public interface TraceRecordMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	int insert(TraceRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	int insertSelective(TraceRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	TraceRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TraceRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trace_record
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TraceRecord record);

	@Select("select count(id) from t_trace_record where contact_hospital_id=#{contactHospitalId}")
	@ResultType(Integer.class)
	int contactHospitalTraceRecordCount(@Param("contactHospitalId") String contactHospitalId);
}