package zasellaid.dao.entity;

public class ClientUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.realname
	 * @mbg.generated
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.password_md5
	 * @mbg.generated
	 */
	private String passwordMd5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.if_loginable
	 * @mbg.generated
	 */
	private Integer ifLoginable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.loginunable_reason
	 * @mbg.generated
	 */
	private String loginunableReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.if_admin
	 * @mbg.generated
	 */
	private Integer ifAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.if_superadmin
	 * @mbg.generated
	 */
	private Integer ifSuperadmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.register_time
	 * @mbg.generated
	 */
	private Long registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.remark
	 * @mbg.generated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.admin_user_id
	 * @mbg.generated
	 */
	private String adminUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.maintain_is
	 * @mbg.generated
	 */
	private Integer maintainIs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_client_user.last_alive_time
	 * @mbg.generated
	 */
	private Long lastAliveTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.id
	 * @return  the value of t_client_user.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.id
	 * @param id  the value for t_client_user.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.phone
	 * @return  the value of t_client_user.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.phone
	 * @param phone  the value for t_client_user.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.realname
	 * @return  the value of t_client_user.realname
	 * @mbg.generated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.realname
	 * @param realname  the value for t_client_user.realname
	 * @mbg.generated
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.password
	 * @return  the value of t_client_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.password
	 * @param password  the value for t_client_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.password_md5
	 * @return  the value of t_client_user.password_md5
	 * @mbg.generated
	 */
	public String getPasswordMd5() {
		return passwordMd5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.password_md5
	 * @param passwordMd5  the value for t_client_user.password_md5
	 * @mbg.generated
	 */
	public void setPasswordMd5(String passwordMd5) {
		this.passwordMd5 = passwordMd5 == null ? null : passwordMd5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.if_loginable
	 * @return  the value of t_client_user.if_loginable
	 * @mbg.generated
	 */
	public Integer getIfLoginable() {
		return ifLoginable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.if_loginable
	 * @param ifLoginable  the value for t_client_user.if_loginable
	 * @mbg.generated
	 */
	public void setIfLoginable(Integer ifLoginable) {
		this.ifLoginable = ifLoginable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.loginunable_reason
	 * @return  the value of t_client_user.loginunable_reason
	 * @mbg.generated
	 */
	public String getLoginunableReason() {
		return loginunableReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.loginunable_reason
	 * @param loginunableReason  the value for t_client_user.loginunable_reason
	 * @mbg.generated
	 */
	public void setLoginunableReason(String loginunableReason) {
		this.loginunableReason = loginunableReason == null ? null : loginunableReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.if_admin
	 * @return  the value of t_client_user.if_admin
	 * @mbg.generated
	 */
	public Integer getIfAdmin() {
		return ifAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.if_admin
	 * @param ifAdmin  the value for t_client_user.if_admin
	 * @mbg.generated
	 */
	public void setIfAdmin(Integer ifAdmin) {
		this.ifAdmin = ifAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.if_superadmin
	 * @return  the value of t_client_user.if_superadmin
	 * @mbg.generated
	 */
	public Integer getIfSuperadmin() {
		return ifSuperadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.if_superadmin
	 * @param ifSuperadmin  the value for t_client_user.if_superadmin
	 * @mbg.generated
	 */
	public void setIfSuperadmin(Integer ifSuperadmin) {
		this.ifSuperadmin = ifSuperadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.register_time
	 * @return  the value of t_client_user.register_time
	 * @mbg.generated
	 */
	public Long getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.register_time
	 * @param registerTime  the value for t_client_user.register_time
	 * @mbg.generated
	 */
	public void setRegisterTime(Long registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.remark
	 * @return  the value of t_client_user.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.remark
	 * @param remark  the value for t_client_user.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.admin_user_id
	 * @return  the value of t_client_user.admin_user_id
	 * @mbg.generated
	 */
	public String getAdminUserId() {
		return adminUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.admin_user_id
	 * @param adminUserId  the value for t_client_user.admin_user_id
	 * @mbg.generated
	 */
	public void setAdminUserId(String adminUserId) {
		this.adminUserId = adminUserId == null ? null : adminUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.maintain_is
	 * @return  the value of t_client_user.maintain_is
	 * @mbg.generated
	 */
	public Integer getMaintainIs() {
		return maintainIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.maintain_is
	 * @param maintainIs  the value for t_client_user.maintain_is
	 * @mbg.generated
	 */
	public void setMaintainIs(Integer maintainIs) {
		this.maintainIs = maintainIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_client_user.last_alive_time
	 * @return  the value of t_client_user.last_alive_time
	 * @mbg.generated
	 */
	public Long getLastAliveTime() {
		return lastAliveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_client_user.last_alive_time
	 * @param lastAliveTime  the value for t_client_user.last_alive_time
	 * @mbg.generated
	 */
	public void setLastAliveTime(Long lastAliveTime) {
		this.lastAliveTime = lastAliveTime;
	}
}