package zasellaid.dao.entity;

public class ContactHospital {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.client_user_id
	 * @mbg.generated
	 */
	private String clientUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.dean_phone
	 * @mbg.generated
	 */
	private String deanPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.dean_name
	 * @mbg.generated
	 */
	private String deanName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.hospital_tel
	 * @mbg.generated
	 */
	private String hospitalTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.department_name
	 * @mbg.generated
	 */
	private String departmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.director_phone
	 * @mbg.generated
	 */
	private String directorPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.province_id
	 * @mbg.generated
	 */
	private Integer provinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.province_name
	 * @mbg.generated
	 */
	private String provinceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.city_id
	 * @mbg.generated
	 */
	private Integer cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.city_name
	 * @mbg.generated
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.customer_type
	 * @mbg.generated
	 */
	private Integer customerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.trace_status
	 * @mbg.generated
	 */
	private Integer traceStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.extra_infos
	 * @mbg.generated
	 */
	private String extraInfos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.add_time
	 * @mbg.generated
	 */
	private Long addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.client_user_del
	 * @mbg.generated
	 */
	private Integer clientUserDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contact_hospital.last_trace_time
	 * @mbg.generated
	 */
	private Long lastTraceTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.id
	 * @return  the value of t_contact_hospital.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.id
	 * @param id  the value for t_contact_hospital.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.client_user_id
	 * @return  the value of t_contact_hospital.client_user_id
	 * @mbg.generated
	 */
	public String getClientUserId() {
		return clientUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.client_user_id
	 * @param clientUserId  the value for t_contact_hospital.client_user_id
	 * @mbg.generated
	 */
	public void setClientUserId(String clientUserId) {
		this.clientUserId = clientUserId == null ? null : clientUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.name
	 * @return  the value of t_contact_hospital.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.name
	 * @param name  the value for t_contact_hospital.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.dean_phone
	 * @return  the value of t_contact_hospital.dean_phone
	 * @mbg.generated
	 */
	public String getDeanPhone() {
		return deanPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.dean_phone
	 * @param deanPhone  the value for t_contact_hospital.dean_phone
	 * @mbg.generated
	 */
	public void setDeanPhone(String deanPhone) {
		this.deanPhone = deanPhone == null ? null : deanPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.dean_name
	 * @return  the value of t_contact_hospital.dean_name
	 * @mbg.generated
	 */
	public String getDeanName() {
		return deanName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.dean_name
	 * @param deanName  the value for t_contact_hospital.dean_name
	 * @mbg.generated
	 */
	public void setDeanName(String deanName) {
		this.deanName = deanName == null ? null : deanName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.hospital_tel
	 * @return  the value of t_contact_hospital.hospital_tel
	 * @mbg.generated
	 */
	public String getHospitalTel() {
		return hospitalTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.hospital_tel
	 * @param hospitalTel  the value for t_contact_hospital.hospital_tel
	 * @mbg.generated
	 */
	public void setHospitalTel(String hospitalTel) {
		this.hospitalTel = hospitalTel == null ? null : hospitalTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.department_name
	 * @return  the value of t_contact_hospital.department_name
	 * @mbg.generated
	 */
	public String getDepartmentName() {
		return departmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.department_name
	 * @param departmentName  the value for t_contact_hospital.department_name
	 * @mbg.generated
	 */
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName == null ? null : departmentName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.director_phone
	 * @return  the value of t_contact_hospital.director_phone
	 * @mbg.generated
	 */
	public String getDirectorPhone() {
		return directorPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.director_phone
	 * @param directorPhone  the value for t_contact_hospital.director_phone
	 * @mbg.generated
	 */
	public void setDirectorPhone(String directorPhone) {
		this.directorPhone = directorPhone == null ? null : directorPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.province_id
	 * @return  the value of t_contact_hospital.province_id
	 * @mbg.generated
	 */
	public Integer getProvinceId() {
		return provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.province_id
	 * @param provinceId  the value for t_contact_hospital.province_id
	 * @mbg.generated
	 */
	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.province_name
	 * @return  the value of t_contact_hospital.province_name
	 * @mbg.generated
	 */
	public String getProvinceName() {
		return provinceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.province_name
	 * @param provinceName  the value for t_contact_hospital.province_name
	 * @mbg.generated
	 */
	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName == null ? null : provinceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.city_id
	 * @return  the value of t_contact_hospital.city_id
	 * @mbg.generated
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.city_id
	 * @param cityId  the value for t_contact_hospital.city_id
	 * @mbg.generated
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.city_name
	 * @return  the value of t_contact_hospital.city_name
	 * @mbg.generated
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.city_name
	 * @param cityName  the value for t_contact_hospital.city_name
	 * @mbg.generated
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.customer_type
	 * @return  the value of t_contact_hospital.customer_type
	 * @mbg.generated
	 */
	public Integer getCustomerType() {
		return customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.customer_type
	 * @param customerType  the value for t_contact_hospital.customer_type
	 * @mbg.generated
	 */
	public void setCustomerType(Integer customerType) {
		this.customerType = customerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.trace_status
	 * @return  the value of t_contact_hospital.trace_status
	 * @mbg.generated
	 */
	public Integer getTraceStatus() {
		return traceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.trace_status
	 * @param traceStatus  the value for t_contact_hospital.trace_status
	 * @mbg.generated
	 */
	public void setTraceStatus(Integer traceStatus) {
		this.traceStatus = traceStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.extra_infos
	 * @return  the value of t_contact_hospital.extra_infos
	 * @mbg.generated
	 */
	public String getExtraInfos() {
		return extraInfos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.extra_infos
	 * @param extraInfos  the value for t_contact_hospital.extra_infos
	 * @mbg.generated
	 */
	public void setExtraInfos(String extraInfos) {
		this.extraInfos = extraInfos == null ? null : extraInfos.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.add_time
	 * @return  the value of t_contact_hospital.add_time
	 * @mbg.generated
	 */
	public Long getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.add_time
	 * @param addTime  the value for t_contact_hospital.add_time
	 * @mbg.generated
	 */
	public void setAddTime(Long addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.client_user_del
	 * @return  the value of t_contact_hospital.client_user_del
	 * @mbg.generated
	 */
	public Integer getClientUserDel() {
		return clientUserDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.client_user_del
	 * @param clientUserDel  the value for t_contact_hospital.client_user_del
	 * @mbg.generated
	 */
	public void setClientUserDel(Integer clientUserDel) {
		this.clientUserDel = clientUserDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contact_hospital.last_trace_time
	 * @return  the value of t_contact_hospital.last_trace_time
	 * @mbg.generated
	 */
	public Long getLastTraceTime() {
		return lastTraceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contact_hospital.last_trace_time
	 * @param lastTraceTime  the value for t_contact_hospital.last_trace_time
	 * @mbg.generated
	 */
	public void setLastTraceTime(Long lastTraceTime) {
		this.lastTraceTime = lastTraceTime;
	}
}