package zasellaid.dao.entity;

public class Sysparam {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysparam.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysparam.value
	 * @mbg.generated
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_sysparam.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysparam.id
	 * @return  the value of t_sysparam.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysparam.id
	 * @param id  the value for t_sysparam.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysparam.value
	 * @return  the value of t_sysparam.value
	 * @mbg.generated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysparam.value
	 * @param value  the value for t_sysparam.value
	 * @mbg.generated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_sysparam.remark
	 * @return  the value of t_sysparam.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_sysparam.remark
	 * @param remark  the value for t_sysparam.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}