package zasellaid.dao.entity;

public class TraceRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.type
	 * @mbg.generated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.trace_time
	 * @mbg.generated
	 */
	private Long traceTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.voice_duration
	 * @mbg.generated
	 */
	private Integer voiceDuration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trace_record.contact_hospital_id
	 * @mbg.generated
	 */
	private String contactHospitalId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.id
	 * @return  the value of t_trace_record.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.id
	 * @param id  the value for t_trace_record.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.user_id
	 * @return  the value of t_trace_record.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.user_id
	 * @param userId  the value for t_trace_record.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.type
	 * @return  the value of t_trace_record.type
	 * @mbg.generated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.type
	 * @param type  the value for t_trace_record.type
	 * @mbg.generated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.content
	 * @return  the value of t_trace_record.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.content
	 * @param content  the value for t_trace_record.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.trace_time
	 * @return  the value of t_trace_record.trace_time
	 * @mbg.generated
	 */
	public Long getTraceTime() {
		return traceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.trace_time
	 * @param traceTime  the value for t_trace_record.trace_time
	 * @mbg.generated
	 */
	public void setTraceTime(Long traceTime) {
		this.traceTime = traceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.voice_duration
	 * @return  the value of t_trace_record.voice_duration
	 * @mbg.generated
	 */
	public Integer getVoiceDuration() {
		return voiceDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.voice_duration
	 * @param voiceDuration  the value for t_trace_record.voice_duration
	 * @mbg.generated
	 */
	public void setVoiceDuration(Integer voiceDuration) {
		this.voiceDuration = voiceDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trace_record.contact_hospital_id
	 * @return  the value of t_trace_record.contact_hospital_id
	 * @mbg.generated
	 */
	public String getContactHospitalId() {
		return contactHospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trace_record.contact_hospital_id
	 * @param contactHospitalId  the value for t_trace_record.contact_hospital_id
	 * @mbg.generated
	 */
	public void setContactHospitalId(String contactHospitalId) {
		this.contactHospitalId = contactHospitalId == null ? null : contactHospitalId.trim();
	}
}