package passion.dao.mapper;

import passion.dao.entity.AppRenew;

public interface AppRenewMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	int insert(AppRenew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	int insertSelective(AppRenew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	AppRenew selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(AppRenew record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_app_renew
	 * @mbg.generated
	 */
	int updateByPrimaryKey(AppRenew record);
}