package passion.dao.mapper;

import passion.dao.entity.ClientUser;

public interface ClientUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int insert(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int insertSelective(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	ClientUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ClientUser record);

	
}