package passion.dao.mapper;

import passion.dao.entity.HpActivity;

public interface HpActivityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	int insert(HpActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	int insertSelective(HpActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	HpActivity selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_activity
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpActivity record);
}