package passion.dao.mapper;

import passion.dao.entity.HpClientHomepageFeatureddepartment;

public interface HpClientHomepageFeatureddepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String departmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	int insert(HpClientHomepageFeatureddepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	int insertSelective(HpClientHomepageFeatureddepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	HpClientHomepageFeatureddepartment selectByPrimaryKey(String departmentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpClientHomepageFeatureddepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_homepage_featureddepartment
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpClientHomepageFeatureddepartment record);
}