package passion.dao.mapper;

import passion.dao.entity.HpClientUser;

public interface HpClientUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	int insert(HpClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	int insertSelective(HpClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	HpClientUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpClientUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_client_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpClientUser record);
}