package passion.dao.mapper;

import passion.dao.entity.HpDepartment;

public interface HpDepartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	int insert(HpDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	int insertSelective(HpDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	HpDepartment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpDepartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_department
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpDepartment record);
}