package passion.dao.mapper;

import passion.dao.entity.HpDoctor;

public interface HpDoctorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	int insert(HpDoctor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	int insertSelective(HpDoctor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	HpDoctor selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpDoctor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_doctor
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpDoctor record);
}