package passion.dao.mapper;

import passion.dao.entity.HpHospitalUser;

public interface HpHospitalUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	int insert(HpHospitalUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	int insertSelective(HpHospitalUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	HpHospitalUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpHospitalUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpHospitalUser record);
}