package passion.dao.mapper;

import passion.dao.entity.HpHospital;

public interface HpHospitalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	int insert(HpHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	int insertSelective(HpHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	HpHospital selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpHospital record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_hospital
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpHospital record);
}