package passion.dao.mapper;

import passion.dao.entity.HpProject;

public interface HpProjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	int insert(HpProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	int insertSelective(HpProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	HpProject selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HpProject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_hp_project
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HpProject record);
}