package passion.dao.mapper;

import passion.dao.entity.Shopapp;

public interface ShopappMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	int insert(Shopapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	int insertSelective(Shopapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	Shopapp selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Shopapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopapp
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Shopapp record);
}