package passion.dao.mapper;

import passion.dao.entity.WxMiniapp;

public interface WxMiniappMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	int insert(WxMiniapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	int insertSelective(WxMiniapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	WxMiniapp selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(WxMiniapp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_wx_miniapp
	 * @mbg.generated
	 */
	int updateByPrimaryKey(WxMiniapp record);

	
}