package passion.dao.entity;

import java.math.BigDecimal;

public class AppRenew {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_renew.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_renew.app_id
	 * @mbg.generated
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_renew.buyer_userid
	 * @mbg.generated
	 */
	private String buyerUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_renew.time
	 * @mbg.generated
	 */
	private Long time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_app_renew.money
	 * @mbg.generated
	 */
	private BigDecimal money;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_renew.id
	 * @return  the value of t_app_renew.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_renew.id
	 * @param id  the value for t_app_renew.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_renew.app_id
	 * @return  the value of t_app_renew.app_id
	 * @mbg.generated
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_renew.app_id
	 * @param appId  the value for t_app_renew.app_id
	 * @mbg.generated
	 */
	public void setAppId(String appId) {
		this.appId = appId == null ? null : appId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_renew.buyer_userid
	 * @return  the value of t_app_renew.buyer_userid
	 * @mbg.generated
	 */
	public String getBuyerUserid() {
		return buyerUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_renew.buyer_userid
	 * @param buyerUserid  the value for t_app_renew.buyer_userid
	 * @mbg.generated
	 */
	public void setBuyerUserid(String buyerUserid) {
		this.buyerUserid = buyerUserid == null ? null : buyerUserid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_renew.time
	 * @return  the value of t_app_renew.time
	 * @mbg.generated
	 */
	public Long getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_renew.time
	 * @param time  the value for t_app_renew.time
	 * @mbg.generated
	 */
	public void setTime(Long time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_app_renew.money
	 * @return  the value of t_app_renew.money
	 * @mbg.generated
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_app_renew.money
	 * @param money  the value for t_app_renew.money
	 * @mbg.generated
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}
}