package passion.dao.entity;

public class HpClientHomepageTeamdoctor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_teamdoctor.doctor_id
	 * @mbg.generated
	 */
	private String doctorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_teamdoctor.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_teamdoctor.sequence_no
	 * @mbg.generated
	 */
	private Byte sequenceNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_teamdoctor.doctor_id
	 * @return  the value of t_hp_client_homepage_teamdoctor.doctor_id
	 * @mbg.generated
	 */
	public String getDoctorId() {
		return doctorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_teamdoctor.doctor_id
	 * @param doctorId  the value for t_hp_client_homepage_teamdoctor.doctor_id
	 * @mbg.generated
	 */
	public void setDoctorId(String doctorId) {
		this.doctorId = doctorId == null ? null : doctorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_teamdoctor.hospital_id
	 * @return  the value of t_hp_client_homepage_teamdoctor.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_teamdoctor.hospital_id
	 * @param hospitalId  the value for t_hp_client_homepage_teamdoctor.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_teamdoctor.sequence_no
	 * @return  the value of t_hp_client_homepage_teamdoctor.sequence_no
	 * @mbg.generated
	 */
	public Byte getSequenceNo() {
		return sequenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_teamdoctor.sequence_no
	 * @param sequenceNo  the value for t_hp_client_homepage_teamdoctor.sequence_no
	 * @mbg.generated
	 */
	public void setSequenceNo(Byte sequenceNo) {
		this.sequenceNo = sequenceNo;
	}
}