package passion.dao.entity;

public class HpClientHomepageFeatureddepartment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_featureddepartment.department_id
	 * @mbg.generated
	 */
	private String departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_featureddepartment.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_featureddepartment.sequence_no
	 * @mbg.generated
	 */
	private Byte sequenceNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_featureddepartment.department_id
	 * @return  the value of t_hp_client_homepage_featureddepartment.department_id
	 * @mbg.generated
	 */
	public String getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_featureddepartment.department_id
	 * @param departmentId  the value for t_hp_client_homepage_featureddepartment.department_id
	 * @mbg.generated
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId == null ? null : departmentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_featureddepartment.hospital_id
	 * @return  the value of t_hp_client_homepage_featureddepartment.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_featureddepartment.hospital_id
	 * @param hospitalId  the value for t_hp_client_homepage_featureddepartment.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_featureddepartment.sequence_no
	 * @return  the value of t_hp_client_homepage_featureddepartment.sequence_no
	 * @mbg.generated
	 */
	public Byte getSequenceNo() {
		return sequenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_featureddepartment.sequence_no
	 * @param sequenceNo  the value for t_hp_client_homepage_featureddepartment.sequence_no
	 * @mbg.generated
	 */
	public void setSequenceNo(Byte sequenceNo) {
		this.sequenceNo = sequenceNo;
	}
}