package passion.dao.entity;

public class HpClientHomepageRollpicture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.type
	 * @mbg.generated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.picture
	 * @mbg.generated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.sequence_no
	 * @mbg.generated
	 */
	private Byte sequenceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.link_id
	 * @mbg.generated
	 */
	private String linkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_homepage_rollpicture.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.id
	 * @return  the value of t_hp_client_homepage_rollpicture.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.id
	 * @param id  the value for t_hp_client_homepage_rollpicture.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.type
	 * @return  the value of t_hp_client_homepage_rollpicture.type
	 * @mbg.generated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.type
	 * @param type  the value for t_hp_client_homepage_rollpicture.type
	 * @mbg.generated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.picture
	 * @return  the value of t_hp_client_homepage_rollpicture.picture
	 * @mbg.generated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.picture
	 * @param picture  the value for t_hp_client_homepage_rollpicture.picture
	 * @mbg.generated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.sequence_no
	 * @return  the value of t_hp_client_homepage_rollpicture.sequence_no
	 * @mbg.generated
	 */
	public Byte getSequenceNo() {
		return sequenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.sequence_no
	 * @param sequenceNo  the value for t_hp_client_homepage_rollpicture.sequence_no
	 * @mbg.generated
	 */
	public void setSequenceNo(Byte sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.link_id
	 * @return  the value of t_hp_client_homepage_rollpicture.link_id
	 * @mbg.generated
	 */
	public String getLinkId() {
		return linkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.link_id
	 * @param linkId  the value for t_hp_client_homepage_rollpicture.link_id
	 * @mbg.generated
	 */
	public void setLinkId(String linkId) {
		this.linkId = linkId == null ? null : linkId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_homepage_rollpicture.hospital_id
	 * @return  the value of t_hp_client_homepage_rollpicture.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_homepage_rollpicture.hospital_id
	 * @param hospitalId  the value for t_hp_client_homepage_rollpicture.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}
}