package passion.dao.entity;

public class HpClientUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.nickname
	 * @mbg.generated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.password_md5
	 * @mbg.generated
	 */
	private String passwordMd5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.if_loginable
	 * @mbg.generated
	 */
	private Byte ifLoginable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.loginunable_reason
	 * @mbg.generated
	 */
	private String loginunableReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.if_admin
	 * @mbg.generated
	 */
	private Byte ifAdmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.if_superadmin
	 * @mbg.generated
	 */
	private Byte ifSuperadmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.register_time
	 * @mbg.generated
	 */
	private Long registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.wx_open_id
	 * @mbg.generated
	 */
	private String wxOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_client_user.wx_session_key
	 * @mbg.generated
	 */
	private String wxSessionKey;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.id
	 * @return  the value of t_hp_client_user.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.id
	 * @param id  the value for t_hp_client_user.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.hospital_id
	 * @return  the value of t_hp_client_user.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.hospital_id
	 * @param hospitalId  the value for t_hp_client_user.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.username
	 * @return  the value of t_hp_client_user.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.username
	 * @param username  the value for t_hp_client_user.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.phone
	 * @return  the value of t_hp_client_user.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.phone
	 * @param phone  the value for t_hp_client_user.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.nickname
	 * @return  the value of t_hp_client_user.nickname
	 * @mbg.generated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.nickname
	 * @param nickname  the value for t_hp_client_user.nickname
	 * @mbg.generated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.password
	 * @return  the value of t_hp_client_user.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.password
	 * @param password  the value for t_hp_client_user.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.password_md5
	 * @return  the value of t_hp_client_user.password_md5
	 * @mbg.generated
	 */
	public String getPasswordMd5() {
		return passwordMd5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.password_md5
	 * @param passwordMd5  the value for t_hp_client_user.password_md5
	 * @mbg.generated
	 */
	public void setPasswordMd5(String passwordMd5) {
		this.passwordMd5 = passwordMd5 == null ? null : passwordMd5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.if_loginable
	 * @return  the value of t_hp_client_user.if_loginable
	 * @mbg.generated
	 */
	public Byte getIfLoginable() {
		return ifLoginable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.if_loginable
	 * @param ifLoginable  the value for t_hp_client_user.if_loginable
	 * @mbg.generated
	 */
	public void setIfLoginable(Byte ifLoginable) {
		this.ifLoginable = ifLoginable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.loginunable_reason
	 * @return  the value of t_hp_client_user.loginunable_reason
	 * @mbg.generated
	 */
	public String getLoginunableReason() {
		return loginunableReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.loginunable_reason
	 * @param loginunableReason  the value for t_hp_client_user.loginunable_reason
	 * @mbg.generated
	 */
	public void setLoginunableReason(String loginunableReason) {
		this.loginunableReason = loginunableReason == null ? null : loginunableReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.if_admin
	 * @return  the value of t_hp_client_user.if_admin
	 * @mbg.generated
	 */
	public Byte getIfAdmin() {
		return ifAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.if_admin
	 * @param ifAdmin  the value for t_hp_client_user.if_admin
	 * @mbg.generated
	 */
	public void setIfAdmin(Byte ifAdmin) {
		this.ifAdmin = ifAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.if_superadmin
	 * @return  the value of t_hp_client_user.if_superadmin
	 * @mbg.generated
	 */
	public Byte getIfSuperadmin() {
		return ifSuperadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.if_superadmin
	 * @param ifSuperadmin  the value for t_hp_client_user.if_superadmin
	 * @mbg.generated
	 */
	public void setIfSuperadmin(Byte ifSuperadmin) {
		this.ifSuperadmin = ifSuperadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.register_time
	 * @return  the value of t_hp_client_user.register_time
	 * @mbg.generated
	 */
	public Long getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.register_time
	 * @param registerTime  the value for t_hp_client_user.register_time
	 * @mbg.generated
	 */
	public void setRegisterTime(Long registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.wx_open_id
	 * @return  the value of t_hp_client_user.wx_open_id
	 * @mbg.generated
	 */
	public String getWxOpenId() {
		return wxOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.wx_open_id
	 * @param wxOpenId  the value for t_hp_client_user.wx_open_id
	 * @mbg.generated
	 */
	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_client_user.wx_session_key
	 * @return  the value of t_hp_client_user.wx_session_key
	 * @mbg.generated
	 */
	public String getWxSessionKey() {
		return wxSessionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_client_user.wx_session_key
	 * @param wxSessionKey  the value for t_hp_client_user.wx_session_key
	 * @mbg.generated
	 */
	public void setWxSessionKey(String wxSessionKey) {
		this.wxSessionKey = wxSessionKey == null ? null : wxSessionKey.trim();
	}
}