package passion.dao.entity;

public class HpDepartment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_department.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_department.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_department.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_department.picture
	 * @mbg.generated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_department.introduction
	 * @mbg.generated
	 */
	private String introduction;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_department.id
	 * @return  the value of t_hp_department.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_department.id
	 * @param id  the value for t_hp_department.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_department.hospital_id
	 * @return  the value of t_hp_department.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_department.hospital_id
	 * @param hospitalId  the value for t_hp_department.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_department.name
	 * @return  the value of t_hp_department.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_department.name
	 * @param name  the value for t_hp_department.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_department.picture
	 * @return  the value of t_hp_department.picture
	 * @mbg.generated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_department.picture
	 * @param picture  the value for t_hp_department.picture
	 * @mbg.generated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_department.introduction
	 * @return  the value of t_hp_department.introduction
	 * @mbg.generated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_department.introduction
	 * @param introduction  the value for t_hp_department.introduction
	 * @mbg.generated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}
}