package passion.dao.entity;

public class HpDoctor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.photo
	 * @mbg.generated
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.jobtitle
	 * @mbg.generated
	 */
	private String jobtitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_doctor.introduction
	 * @mbg.generated
	 */
	private String introduction;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.id
	 * @return  the value of t_hp_doctor.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.id
	 * @param id  the value for t_hp_doctor.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.hospital_id
	 * @return  the value of t_hp_doctor.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.hospital_id
	 * @param hospitalId  the value for t_hp_doctor.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.name
	 * @return  the value of t_hp_doctor.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.name
	 * @param name  the value for t_hp_doctor.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.photo
	 * @return  the value of t_hp_doctor.photo
	 * @mbg.generated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.photo
	 * @param photo  the value for t_hp_doctor.photo
	 * @mbg.generated
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.jobtitle
	 * @return  the value of t_hp_doctor.jobtitle
	 * @mbg.generated
	 */
	public String getJobtitle() {
		return jobtitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.jobtitle
	 * @param jobtitle  the value for t_hp_doctor.jobtitle
	 * @mbg.generated
	 */
	public void setJobtitle(String jobtitle) {
		this.jobtitle = jobtitle == null ? null : jobtitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_doctor.introduction
	 * @return  the value of t_hp_doctor.introduction
	 * @mbg.generated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_doctor.introduction
	 * @param introduction  the value for t_hp_doctor.introduction
	 * @mbg.generated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}
}