package passion.dao.entity;

public class HpHospital {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.hospital_name
	 * @mbg.generated
	 */
	private String hospitalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.wx_miniapp_Id
	 * @mbg.generated
	 */
	private String wxMiniappId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.introduction
	 * @mbg.generated
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.picture
	 * @mbg.generated
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_hospital.entering_time
	 * @mbg.generated
	 */
	private Long enteringTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.id
	 * @return  the value of t_hp_hospital.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.id
	 * @param id  the value for t_hp_hospital.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.hospital_name
	 * @return  the value of t_hp_hospital.hospital_name
	 * @mbg.generated
	 */
	public String getHospitalName() {
		return hospitalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.hospital_name
	 * @param hospitalName  the value for t_hp_hospital.hospital_name
	 * @mbg.generated
	 */
	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName == null ? null : hospitalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.wx_miniapp_Id
	 * @return  the value of t_hp_hospital.wx_miniapp_Id
	 * @mbg.generated
	 */
	public String getWxMiniappId() {
		return wxMiniappId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.wx_miniapp_Id
	 * @param wxMiniappId  the value for t_hp_hospital.wx_miniapp_Id
	 * @mbg.generated
	 */
	public void setWxMiniappId(String wxMiniappId) {
		this.wxMiniappId = wxMiniappId == null ? null : wxMiniappId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.introduction
	 * @return  the value of t_hp_hospital.introduction
	 * @mbg.generated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.introduction
	 * @param introduction  the value for t_hp_hospital.introduction
	 * @mbg.generated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.picture
	 * @return  the value of t_hp_hospital.picture
	 * @mbg.generated
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.picture
	 * @param picture  the value for t_hp_hospital.picture
	 * @mbg.generated
	 */
	public void setPicture(String picture) {
		this.picture = picture == null ? null : picture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_hospital.entering_time
	 * @return  the value of t_hp_hospital.entering_time
	 * @mbg.generated
	 */
	public Long getEnteringTime() {
		return enteringTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_hospital.entering_time
	 * @param enteringTime  the value for t_hp_hospital.entering_time
	 * @mbg.generated
	 */
	public void setEnteringTime(Long enteringTime) {
		this.enteringTime = enteringTime;
	}
}