package passion.dao.entity;

public class HpProject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.hospital_id
	 * @mbg.generated
	 */
	private String hospitalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.title_picture
	 * @mbg.generated
	 */
	private String titlePicture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_hp_project.create_time
	 * @mbg.generated
	 */
	private Long createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.id
	 * @return  the value of t_hp_project.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.id
	 * @param id  the value for t_hp_project.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.hospital_id
	 * @return  the value of t_hp_project.hospital_id
	 * @mbg.generated
	 */
	public String getHospitalId() {
		return hospitalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.hospital_id
	 * @param hospitalId  the value for t_hp_project.hospital_id
	 * @mbg.generated
	 */
	public void setHospitalId(String hospitalId) {
		this.hospitalId = hospitalId == null ? null : hospitalId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.title
	 * @return  the value of t_hp_project.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.title
	 * @param title  the value for t_hp_project.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.title_picture
	 * @return  the value of t_hp_project.title_picture
	 * @mbg.generated
	 */
	public String getTitlePicture() {
		return titlePicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.title_picture
	 * @param titlePicture  the value for t_hp_project.title_picture
	 * @mbg.generated
	 */
	public void setTitlePicture(String titlePicture) {
		this.titlePicture = titlePicture == null ? null : titlePicture.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.content
	 * @return  the value of t_hp_project.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.content
	 * @param content  the value for t_hp_project.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_hp_project.create_time
	 * @return  the value of t_hp_project.create_time
	 * @mbg.generated
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_hp_project.create_time
	 * @param createTime  the value for t_hp_project.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
}