package passion.dao.entity;

import java.math.BigDecimal;

public class Shopapp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.lastest_template_id
	 * @mbg.generated
	 */
	private String lastestTemplateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.price
	 * @mbg.generated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.icon
	 * @mbg.generated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.summary
	 * @mbg.generated
	 */
	private String summary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.intro_pic
	 * @mbg.generated
	 */
	private String introPic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.create_time
	 * @mbg.generated
	 */
	private Long createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopapp.remark
	 * @mbg.generated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.id
	 * @return  the value of t_shopapp.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.id
	 * @param id  the value for t_shopapp.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.lastest_template_id
	 * @return  the value of t_shopapp.lastest_template_id
	 * @mbg.generated
	 */
	public String getLastestTemplateId() {
		return lastestTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.lastest_template_id
	 * @param lastestTemplateId  the value for t_shopapp.lastest_template_id
	 * @mbg.generated
	 */
	public void setLastestTemplateId(String lastestTemplateId) {
		this.lastestTemplateId = lastestTemplateId == null ? null : lastestTemplateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.price
	 * @return  the value of t_shopapp.price
	 * @mbg.generated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.price
	 * @param price  the value for t_shopapp.price
	 * @mbg.generated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.icon
	 * @return  the value of t_shopapp.icon
	 * @mbg.generated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.icon
	 * @param icon  the value for t_shopapp.icon
	 * @mbg.generated
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.name
	 * @return  the value of t_shopapp.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.name
	 * @param name  the value for t_shopapp.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.summary
	 * @return  the value of t_shopapp.summary
	 * @mbg.generated
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.summary
	 * @param summary  the value for t_shopapp.summary
	 * @mbg.generated
	 */
	public void setSummary(String summary) {
		this.summary = summary == null ? null : summary.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.intro_pic
	 * @return  the value of t_shopapp.intro_pic
	 * @mbg.generated
	 */
	public String getIntroPic() {
		return introPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.intro_pic
	 * @param introPic  the value for t_shopapp.intro_pic
	 * @mbg.generated
	 */
	public void setIntroPic(String introPic) {
		this.introPic = introPic == null ? null : introPic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.create_time
	 * @return  the value of t_shopapp.create_time
	 * @mbg.generated
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.create_time
	 * @param createTime  the value for t_shopapp.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopapp.remark
	 * @return  the value of t_shopapp.remark
	 * @mbg.generated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopapp.remark
	 * @param remark  the value for t_shopapp.remark
	 * @mbg.generated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}