package passion.dao.entity;

public class WxMiniapp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.shopapp_id
	 * @mbg.generated
	 */
	private String shopappId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.template_id
	 * @mbg.generated
	 */
	private String templateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.authorized
	 * @mbg.generated
	 */
	private Byte authorized;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.code_commit
	 * @mbg.generated
	 */
	private Byte codeCommit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.submit_audit
	 * @mbg.generated
	 */
	private Byte submitAudit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.released
	 * @mbg.generated
	 */
	private Byte released;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.audit_status
	 * @mbg.generated
	 */
	private Byte auditStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.audit_fail_reason
	 * @mbg.generated
	 */
	private String auditFailReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.audit_id
	 * @mbg.generated
	 */
	private Integer auditId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.show_status
	 * @mbg.generated
	 */
	private Byte showStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.app_id
	 * @mbg.generated
	 */
	private String appId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.access_token
	 * @mbg.generated
	 */
	private String accessToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.expires_in
	 * @mbg.generated
	 */
	private Short expiresIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.refresh_token
	 * @mbg.generated
	 */
	private String refreshToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.func_info
	 * @mbg.generated
	 */
	private String funcInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.nick_name
	 * @mbg.generated
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.head_img
	 * @mbg.generated
	 */
	private String headImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.service_type_info
	 * @mbg.generated
	 */
	private String serviceTypeInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.verify_type_info
	 * @mbg.generated
	 */
	private String verifyTypeInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.user_name
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.principal_name
	 * @mbg.generated
	 */
	private String principalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.business_info
	 * @mbg.generated
	 */
	private String businessInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.qrcode_url
	 * @mbg.generated
	 */
	private String qrcodeUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.signature
	 * @mbg.generated
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.authorization_time
	 * @mbg.generated
	 */
	private Long authorizationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.bind_time
	 * @mbg.generated
	 */
	private Long bindTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.committed_template_id
	 * @mbg.generated
	 */
	private String committedTemplateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.auditted_template_id
	 * @mbg.generated
	 */
	private String audittedTemplateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp.use_endtime
	 * @mbg.generated
	 */
	private Long useEndtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.id
	 * @return  the value of t_wx_miniapp.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.id
	 * @param id  the value for t_wx_miniapp.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.user_id
	 * @return  the value of t_wx_miniapp.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.user_id
	 * @param userId  the value for t_wx_miniapp.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.shopapp_id
	 * @return  the value of t_wx_miniapp.shopapp_id
	 * @mbg.generated
	 */
	public String getShopappId() {
		return shopappId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.shopapp_id
	 * @param shopappId  the value for t_wx_miniapp.shopapp_id
	 * @mbg.generated
	 */
	public void setShopappId(String shopappId) {
		this.shopappId = shopappId == null ? null : shopappId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.template_id
	 * @return  the value of t_wx_miniapp.template_id
	 * @mbg.generated
	 */
	public String getTemplateId() {
		return templateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.template_id
	 * @param templateId  the value for t_wx_miniapp.template_id
	 * @mbg.generated
	 */
	public void setTemplateId(String templateId) {
		this.templateId = templateId == null ? null : templateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.authorized
	 * @return  the value of t_wx_miniapp.authorized
	 * @mbg.generated
	 */
	public Byte getAuthorized() {
		return authorized;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.authorized
	 * @param authorized  the value for t_wx_miniapp.authorized
	 * @mbg.generated
	 */
	public void setAuthorized(Byte authorized) {
		this.authorized = authorized;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.code_commit
	 * @return  the value of t_wx_miniapp.code_commit
	 * @mbg.generated
	 */
	public Byte getCodeCommit() {
		return codeCommit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.code_commit
	 * @param codeCommit  the value for t_wx_miniapp.code_commit
	 * @mbg.generated
	 */
	public void setCodeCommit(Byte codeCommit) {
		this.codeCommit = codeCommit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.submit_audit
	 * @return  the value of t_wx_miniapp.submit_audit
	 * @mbg.generated
	 */
	public Byte getSubmitAudit() {
		return submitAudit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.submit_audit
	 * @param submitAudit  the value for t_wx_miniapp.submit_audit
	 * @mbg.generated
	 */
	public void setSubmitAudit(Byte submitAudit) {
		this.submitAudit = submitAudit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.released
	 * @return  the value of t_wx_miniapp.released
	 * @mbg.generated
	 */
	public Byte getReleased() {
		return released;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.released
	 * @param released  the value for t_wx_miniapp.released
	 * @mbg.generated
	 */
	public void setReleased(Byte released) {
		this.released = released;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.audit_status
	 * @return  the value of t_wx_miniapp.audit_status
	 * @mbg.generated
	 */
	public Byte getAuditStatus() {
		return auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.audit_status
	 * @param auditStatus  the value for t_wx_miniapp.audit_status
	 * @mbg.generated
	 */
	public void setAuditStatus(Byte auditStatus) {
		this.auditStatus = auditStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.audit_fail_reason
	 * @return  the value of t_wx_miniapp.audit_fail_reason
	 * @mbg.generated
	 */
	public String getAuditFailReason() {
		return auditFailReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.audit_fail_reason
	 * @param auditFailReason  the value for t_wx_miniapp.audit_fail_reason
	 * @mbg.generated
	 */
	public void setAuditFailReason(String auditFailReason) {
		this.auditFailReason = auditFailReason == null ? null : auditFailReason.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.audit_id
	 * @return  the value of t_wx_miniapp.audit_id
	 * @mbg.generated
	 */
	public Integer getAuditId() {
		return auditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.audit_id
	 * @param auditId  the value for t_wx_miniapp.audit_id
	 * @mbg.generated
	 */
	public void setAuditId(Integer auditId) {
		this.auditId = auditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.show_status
	 * @return  the value of t_wx_miniapp.show_status
	 * @mbg.generated
	 */
	public Byte getShowStatus() {
		return showStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.show_status
	 * @param showStatus  the value for t_wx_miniapp.show_status
	 * @mbg.generated
	 */
	public void setShowStatus(Byte showStatus) {
		this.showStatus = showStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.app_id
	 * @return  the value of t_wx_miniapp.app_id
	 * @mbg.generated
	 */
	public String getAppId() {
		return appId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.app_id
	 * @param appId  the value for t_wx_miniapp.app_id
	 * @mbg.generated
	 */
	public void setAppId(String appId) {
		this.appId = appId == null ? null : appId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.access_token
	 * @return  the value of t_wx_miniapp.access_token
	 * @mbg.generated
	 */
	public String getAccessToken() {
		return accessToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.access_token
	 * @param accessToken  the value for t_wx_miniapp.access_token
	 * @mbg.generated
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken == null ? null : accessToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.expires_in
	 * @return  the value of t_wx_miniapp.expires_in
	 * @mbg.generated
	 */
	public Short getExpiresIn() {
		return expiresIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.expires_in
	 * @param expiresIn  the value for t_wx_miniapp.expires_in
	 * @mbg.generated
	 */
	public void setExpiresIn(Short expiresIn) {
		this.expiresIn = expiresIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.refresh_token
	 * @return  the value of t_wx_miniapp.refresh_token
	 * @mbg.generated
	 */
	public String getRefreshToken() {
		return refreshToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.refresh_token
	 * @param refreshToken  the value for t_wx_miniapp.refresh_token
	 * @mbg.generated
	 */
	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken == null ? null : refreshToken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.func_info
	 * @return  the value of t_wx_miniapp.func_info
	 * @mbg.generated
	 */
	public String getFuncInfo() {
		return funcInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.func_info
	 * @param funcInfo  the value for t_wx_miniapp.func_info
	 * @mbg.generated
	 */
	public void setFuncInfo(String funcInfo) {
		this.funcInfo = funcInfo == null ? null : funcInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.nick_name
	 * @return  the value of t_wx_miniapp.nick_name
	 * @mbg.generated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.nick_name
	 * @param nickName  the value for t_wx_miniapp.nick_name
	 * @mbg.generated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.head_img
	 * @return  the value of t_wx_miniapp.head_img
	 * @mbg.generated
	 */
	public String getHeadImg() {
		return headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.head_img
	 * @param headImg  the value for t_wx_miniapp.head_img
	 * @mbg.generated
	 */
	public void setHeadImg(String headImg) {
		this.headImg = headImg == null ? null : headImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.service_type_info
	 * @return  the value of t_wx_miniapp.service_type_info
	 * @mbg.generated
	 */
	public String getServiceTypeInfo() {
		return serviceTypeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.service_type_info
	 * @param serviceTypeInfo  the value for t_wx_miniapp.service_type_info
	 * @mbg.generated
	 */
	public void setServiceTypeInfo(String serviceTypeInfo) {
		this.serviceTypeInfo = serviceTypeInfo == null ? null : serviceTypeInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.verify_type_info
	 * @return  the value of t_wx_miniapp.verify_type_info
	 * @mbg.generated
	 */
	public String getVerifyTypeInfo() {
		return verifyTypeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.verify_type_info
	 * @param verifyTypeInfo  the value for t_wx_miniapp.verify_type_info
	 * @mbg.generated
	 */
	public void setVerifyTypeInfo(String verifyTypeInfo) {
		this.verifyTypeInfo = verifyTypeInfo == null ? null : verifyTypeInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.user_name
	 * @return  the value of t_wx_miniapp.user_name
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.user_name
	 * @param userName  the value for t_wx_miniapp.user_name
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.principal_name
	 * @return  the value of t_wx_miniapp.principal_name
	 * @mbg.generated
	 */
	public String getPrincipalName() {
		return principalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.principal_name
	 * @param principalName  the value for t_wx_miniapp.principal_name
	 * @mbg.generated
	 */
	public void setPrincipalName(String principalName) {
		this.principalName = principalName == null ? null : principalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.business_info
	 * @return  the value of t_wx_miniapp.business_info
	 * @mbg.generated
	 */
	public String getBusinessInfo() {
		return businessInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.business_info
	 * @param businessInfo  the value for t_wx_miniapp.business_info
	 * @mbg.generated
	 */
	public void setBusinessInfo(String businessInfo) {
		this.businessInfo = businessInfo == null ? null : businessInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.qrcode_url
	 * @return  the value of t_wx_miniapp.qrcode_url
	 * @mbg.generated
	 */
	public String getQrcodeUrl() {
		return qrcodeUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.qrcode_url
	 * @param qrcodeUrl  the value for t_wx_miniapp.qrcode_url
	 * @mbg.generated
	 */
	public void setQrcodeUrl(String qrcodeUrl) {
		this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.signature
	 * @return  the value of t_wx_miniapp.signature
	 * @mbg.generated
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.signature
	 * @param signature  the value for t_wx_miniapp.signature
	 * @mbg.generated
	 */
	public void setSignature(String signature) {
		this.signature = signature == null ? null : signature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.authorization_time
	 * @return  the value of t_wx_miniapp.authorization_time
	 * @mbg.generated
	 */
	public Long getAuthorizationTime() {
		return authorizationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.authorization_time
	 * @param authorizationTime  the value for t_wx_miniapp.authorization_time
	 * @mbg.generated
	 */
	public void setAuthorizationTime(Long authorizationTime) {
		this.authorizationTime = authorizationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.bind_time
	 * @return  the value of t_wx_miniapp.bind_time
	 * @mbg.generated
	 */
	public Long getBindTime() {
		return bindTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.bind_time
	 * @param bindTime  the value for t_wx_miniapp.bind_time
	 * @mbg.generated
	 */
	public void setBindTime(Long bindTime) {
		this.bindTime = bindTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.committed_template_id
	 * @return  the value of t_wx_miniapp.committed_template_id
	 * @mbg.generated
	 */
	public String getCommittedTemplateId() {
		return committedTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.committed_template_id
	 * @param committedTemplateId  the value for t_wx_miniapp.committed_template_id
	 * @mbg.generated
	 */
	public void setCommittedTemplateId(String committedTemplateId) {
		this.committedTemplateId = committedTemplateId == null ? null : committedTemplateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.auditted_template_id
	 * @return  the value of t_wx_miniapp.auditted_template_id
	 * @mbg.generated
	 */
	public String getAudittedTemplateId() {
		return audittedTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.auditted_template_id
	 * @param audittedTemplateId  the value for t_wx_miniapp.auditted_template_id
	 * @mbg.generated
	 */
	public void setAudittedTemplateId(String audittedTemplateId) {
		this.audittedTemplateId = audittedTemplateId == null ? null : audittedTemplateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp.use_endtime
	 * @return  the value of t_wx_miniapp.use_endtime
	 * @mbg.generated
	 */
	public Long getUseEndtime() {
		return useEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp.use_endtime
	 * @param useEndtime  the value for t_wx_miniapp.use_endtime
	 * @mbg.generated
	 */
	public void setUseEndtime(Long useEndtime) {
		this.useEndtime = useEndtime;
	}

}