package passion.dao.entity;

import java.math.BigDecimal;

public class WxMiniappTemplate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.shopapp_id
	 * @mbg.generated
	 */
	private String shopappId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.wx_appid
	 * @mbg.generated
	 */
	private String wxAppid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.wx_template_id
	 * @mbg.generated
	 */
	private Integer wxTemplateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.user_version
	 * @mbg.generated
	 */
	private String userVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.user_desc
	 * @mbg.generated
	 */
	private String userDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_wx_miniapp_template.create_time
	 * @mbg.generated
	 */
	private Long createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.id
	 * @return  the value of t_wx_miniapp_template.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.id
	 * @param id  the value for t_wx_miniapp_template.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.shopapp_id
	 * @return  the value of t_wx_miniapp_template.shopapp_id
	 * @mbg.generated
	 */
	public String getShopappId() {
		return shopappId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.shopapp_id
	 * @param shopappId  the value for t_wx_miniapp_template.shopapp_id
	 * @mbg.generated
	 */
	public void setShopappId(String shopappId) {
		this.shopappId = shopappId == null ? null : shopappId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.wx_appid
	 * @return  the value of t_wx_miniapp_template.wx_appid
	 * @mbg.generated
	 */
	public String getWxAppid() {
		return wxAppid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.wx_appid
	 * @param wxAppid  the value for t_wx_miniapp_template.wx_appid
	 * @mbg.generated
	 */
	public void setWxAppid(String wxAppid) {
		this.wxAppid = wxAppid == null ? null : wxAppid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.wx_template_id
	 * @return  the value of t_wx_miniapp_template.wx_template_id
	 * @mbg.generated
	 */
	public Integer getWxTemplateId() {
		return wxTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.wx_template_id
	 * @param wxTemplateId  the value for t_wx_miniapp_template.wx_template_id
	 * @mbg.generated
	 */
	public void setWxTemplateId(Integer wxTemplateId) {
		this.wxTemplateId = wxTemplateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.user_version
	 * @return  the value of t_wx_miniapp_template.user_version
	 * @mbg.generated
	 */
	public String getUserVersion() {
		return userVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.user_version
	 * @param userVersion  the value for t_wx_miniapp_template.user_version
	 * @mbg.generated
	 */
	public void setUserVersion(String userVersion) {
		this.userVersion = userVersion == null ? null : userVersion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.user_desc
	 * @return  the value of t_wx_miniapp_template.user_desc
	 * @mbg.generated
	 */
	public String getUserDesc() {
		return userDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.user_desc
	 * @param userDesc  the value for t_wx_miniapp_template.user_desc
	 * @mbg.generated
	 */
	public void setUserDesc(String userDesc) {
		this.userDesc = userDesc == null ? null : userDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_wx_miniapp_template.create_time
	 * @return  the value of t_wx_miniapp_template.create_time
	 * @mbg.generated
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_wx_miniapp_template.create_time
	 * @param createTime  the value for t_wx_miniapp_template.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
}